version: '3.7'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./src:/usr/share/nginx/html
      - ./configs/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  php:
    image: vinsonio/php-fpm:latest
    container_name: php
    restart: unless-stopped
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    networks:
      - laravel

networks: 
  laravel:
